# Generated by Django 4.1.5 on 2023-01-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
