# Generated by Django 4.1.5 on 2023-01-21 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
