# Generated by Django 4.1.5 on 2023-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
