# Generated by Django 4.1.5 on 2023-01-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_shippinginfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
