# Generated by Django 4.1.5 on 2023-01-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-ordered"]},
        ),
    ]
