# Generated by Django 4.1.5 on 2023-01-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_orderitem_id_alter_shippinginfo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to=""
            ),
        ),
    ]
