# Generated by Django 4.1.5 on 2023-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_slug_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
